name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Check out code"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 1

      - name: "Set up Go"
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.20.x'

      - name: "Compile main package (fast fail gate)"
        run: go build .

      - name: Install UPX
        uses: crazy-max/ghaction-upx@db8cc9515a4a7ea1b312cb82fbeae6d716daf777 # v3
        with:
          install-only: true
          version: 'v4.2.4'

      - name: UPX version
        run: upx --version

      - name: Build snapshot (goreleaser prebuilt binary)
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: "build --snapshot --clean -f .github/conf/.goreleaser.win7.yml"
