name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.x'

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: UPX version
        run: upx --version

      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Build snapshot
        run: goreleaser build --snapshot --clean
